
title: <p align="center"> Aisharya Ravichandran</p>
logo: /assets/img/Screenshot 2022-03-29 193739.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aisharya-ravichandran-b42b8b80/">LinkedIn</a> |  
  <a href="https://github.com/Aisharya16">GitHub</a>
  
  
  
  <br>   
    I am working as Application analyst for Anthem Digital platform <br>
    
    Worked on supporting various technolies like APIGEE, REST and WeB services, docker, mongodb<br>
    
    Worked on various tools like Splunk, ServiceNow, Jira<br>
  
  </p>



theme: jekyll-theme-minimal
